package com.ebook.epub.viewer;

public class ViewerErrorInfo {
	
	public static final int CODE_ERROR_FILE_NOT_FOUND 									= 0x10001;
	public static final int CODE_ERROR_CONTENTS_INVALID_STREAM 							= 0x10002;
	public static final int CODE_ERROR_EPUB_META_INF_DIRECTORY_NOT_FOUND 				= 0x10002;	//0x10003
	public static final int CODE_ERROR_PACKAGE_PARSING_FAILED_ELEMENT_NOT_FOUND 		= 0x10101;
	public static final int CODE_ERROR_PACKAGE_PARSING_FAILED_ATTRIBUTE_NOT_FOUND		= 0x10102;
	public static final int CODE_ERROR_PACKAGE_INVALID_XML 								= 0x10103;
	public static final int CODE_ERROR_PACKAGE_NAV_FILE_NAME_DEFINE_DUPLICATION			= 0x10104;
	public static final int CODE_ERROR_CONTAINER_PARSING_FAILED_ELEMENT_NOT_FOUND 		= 0x10201;
	public static final int CODE_ERROR_CONTAINER_PARSING_FAILED_ATTRIBUTE_NOT_FOUND 	= 0x10002;	//0x10202
	public static final int CODE_ERROR_CONTAINER_INVALID_XML 							= 0x10203;
	public static final int CODE_ERROR_NAV_PARSING_FAILED_ELEMENT_NOT_FOUND 			= 0x10301;
	public static final int CODE_ERROR_NAV_PARSING_FAILED_ATTRIBUTE_NOT_FOUND 			= 0x10302;
	public static final int CODE_ERROR_NAV_INVALID_XML 									= 0x10303;
	public static final int CODE_ERROR_NAV_TOC_DUPLICATION								= 0x10304;
	public static final int CODE_ERROR_NAV_LANDMARKS_DUPLICATION 						= 0x10305;
	public static final int CODE_ERROR_NAV_PAGELIST_DUPLICATION							= 0x10306;
	public static final int CODE_ERROR_JSON_PARSING_FAILED 								= 0x10401;
	public static final int CODE_ERROR_INVALID_JSON 									= 0x10402;
	public static final int CODE_ERROR_INVALID_3DPAGE_CURL 								= 0x80001;
	public static final int CODE_ERROR_PACKAGE_PARSING_FAILED_REQUIRED_NOT_FOUND 		= 0x10105;
	
	public static final String MSG_ERROR_FILE_NOT_FOUND 									= "ERROR_FILE_NOT_FOUND";
	public static final String MSG_ERROR_CONTENTS_INVALID_STREAM 							= "ERROR_CONTENTS_INVALID_STREAM";
	public static final String MSG_ERROR_EPUB_META_INF_DIRECTORY_NOT_FOUND 					= "ERROR_EPUB_META_INF_DIRECTORY_NOT_FOUND";
	public static final String MSG_ERROR_PACKAGE_PARSING_FAILED_ELEMENT_NOT_FOUND 			= "ERROR_PACKAGE_PARSING_FAILED, ELEMENT_NOT_FOUND";
	public static final String MSG_ERROR_PACKAGE_PARSING_FAILED_ATTRIBUTE_NOT_FOUND			= "ERROR_PACKAGE_PARSING_FAILED, ATTRIBUTE_NOT_FOUND";
	public static final String MSG_ERROR_PACKAGE_INVALID_XML 								= "ERROR_PACKAGE_NAV_FILE_NAME_NOT_FOUND";
	public static final String MSG_ERROR_PACKAGE_NAV_FILE_NAME_DEFINE_DUPLICATION 			= "ERROR_PACKAGE_NAV_FILE_NAME_DEFINE_DUPLICATION";
	public static final String MSG_ERROR_CONTAINER_PARSING_FAILED_ELEMENT_NOT_FOUND 		= "ERROR_CONTAINER_PARSING_FAILED, ELEMENT_NOT_FOUND";
	public static final String MSG_ERROR_CONTAINER_PARSING_FAILED_ATTRIBUTE_NOT_FOUND 		= "ERROR_CONTAINER_PARSING_FAILED, ATTRIBUTE_NOT_FOUND";
	public static final String MSG_ERROR_CONTAINER_INVALID_XML 								= "ERROR_CONTAINER_INVALID_XML";
	public static final String MSG_ERROR_NAV_PARSING_FAILED_ELEMENT_NOT_FOUND 				= "ERROR_NAV_PARSING_FAILED, ELEMENT_NOT_FOUND";
	public static final String MSG_ERROR_NAV_PARSING_FAILED_ATTRIBUTE_NOT_FOUND 			= "ERROR_NAV_PARSING_FAILED, ATTRIBUTE_NOT_FOUND";
	public static final String MSG_ERROR_NAV_INVALID_XML 									= "ERROR_NAV_INVALID_XML";
	public static final String MSG_ERROR_NAV_TOC_DUPLICATION 								= "ERROR_NAV_TOC_DUPLICATION";
	public static final String MSG_ERROR_NAV_LANDMARKS_DUPLICATION 							= "ERROR_NAV_LANDMARKS_DUPLICATION";
	public static final String MSG_ERROR_NAV_PAGELIST_DUPLICATION							= "ERROR_NAV_PAGELIST_DUPLICATION";
	public static final String MSG_ERROR_JSON_PARSING_FAILED 								= "ERROR_JSON_PARSING_FAILED";
	public static final String MSG_ERROR_INVALID_JSON 										= "ERROR_INVALID_JSON";
	public static final String MSG_ERROR_INVALID_3DPAGE_CURL 								= "ERROR_INVALID_3DPAGE_CURL";
	public static final String MSG_ERROR_ELEMENT_NOT_FOUND									= "ERROR_ELEMENT_NOT_FOUND";
	public static final String MSG_ERROR_ATTRIBUTE_NOT_FOUND								= "ERROR_ATTRIBUTE_NOT_FOUND";
	public static final String MSG_ERROR_INVALID_XML										= "ERROR_INVALID_XML";
	public static final String MSG_ERROR_PACKAGE_PARSING_FAILED_REQUIRED_NOT_FOUND			= "ERROR_PACKAGE_PARSING_FAILED_REQUIRED_NOT_FOUND";
}
